### ISSUE TITLE
Action printout system

### ISSUE THREAD

**Issue by erlend-sh** [Adam-Diehl/rust_strategy_rpg#1]
I love the printout you make for the battle outcome! 💯 

Are you interested in a paid micro-gig to implement something similar for [Shotcaller](https://github.com/amethyst/shotcaller)?

**Comment by Adam-Diehl** [comment]
Potentially, what kind of system you be looking to implement?

**Comment by erlend-sh** [comment]
There’s a bit more explanation here: https://github.com/amethyst/shotcaller/issues/52

Can you send me an email so we can get into the details there? See my profile.
